formatter: "md doc"

version: ""

header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: modules
  include-main: true

sections:
  hide: []
  show:
    - data-sources
    - resources
    - modules
    - inputs
    - outputs
    - providers
    - requirements
    - dependencies
    - notes
    - examples
    - readme

content: ""

output:
  file: "./docs/README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Header }}

    ## examples
    ```hcl
    {{ include "examples/simple/main.tf" }}
    ```

    {{ .Requirements }}

    {{ .Providers }}

    {{ .DataSources }}

    {{ .Resources }}

    {{ .Modules }}

    {{ .Inputs }}

    {{ .Outputs }}

    {{ .Dependencies }}

    {{ .Footer }}

    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
